// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet
// From decision table
// "/data/github/asciidoctorj-decisiontable-extension/src/main/resources/DecisionTableToPlantUMLActivityDiagram.lfet"
// 01.12.2019 00:25
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190905b) build in default

package com.uniqueck.asciidoctorj.lfet.puml.activity;

public final class DecisionTableToPlantUMLActivityDiagramRules
{
    public final void execute(IDecisionTableToPlantUMLActivityDiagram iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=com.uniqueck.asciidoctorj.lfet.puml.activity
        // $$InterfaceTraceAfterRule=true
        // $$InterfaceRuleGroups = true
        // $$InterfaceName=IDecisionTableToPlantUMLActivityDiagram
        // $$InterfaceRulesClassname=DecisionTableToPlantUMLActivityDiagramRules
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 1);
                iface.doGetFirstCondition();
                
                ruleGroup = 2;
                exit = false;
                
                iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 1);
                
                // Rule R01 <----
            }
            else
            {
                if ( iface.isConditionTypeIsOccurenceTable() )
                {
                    if ( iface.isCurrentOccEntryIs() )
                    {
                        if ( iface.isHasMoreConditions() )
                        {
                            // Rule R02 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 2);
                            iface.doElse();
                            iface.doNextCondition();
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 2);
                            
                            // Rule R02 <----
                        }
                        else
                        {
                            // Rule R03 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 3);
                            iface.doElse();
                            iface.doAddListOfActions();
                            
                            exit = true;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 3);
                            
                            // Rule R03 <----
                        }
                    }
                    else
                    {
                        if ( iface.isCurrentOccEntryIsLast() )
                        {
                            if ( iface.isHasMoreConditions() )
                            {
                                // Rule R04 ---->
                                
                                iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 4);
                                iface.doElseIfConditionTitleWithOccEntryAndLabelYes();
                                
                                exit = true;
                                
                                iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 4);
                                
                                // Rule R04 <----
                            }
                            else
                            {
                                // Rule R05 ---->
                                
                                iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 5);
                                iface.doElseIfConditionTitleWithOccEntryAndLabelYes();
                                iface.doAddListOfActions();
                                
                                exit = true;
                                
                                iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 5);
                                
                                // Rule R05 <----
                            }
                        }
                        else
                        {
                            if ( iface.isCurrentOccEntryIsFirst() )
                            {
                                if ( iface.isHasMoreConditions() )
                                {
                                    // Rule R06 ---->
                                    
                                    iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 6);
                                    iface.doIfConditionTitleWithOccEntryAndLabelYes();
                                    
                                    exit = true;
                                    
                                    iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 6);
                                    
                                    // Rule R06 <----
                                }
                                else
                                {
                                    // Rule R07 ---->
                                    
                                    iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 7);
                                    iface.doIfConditionTitleWithOccEntryAndLabelYes();
                                    iface.doAddListOfActions();
                                    iface.doNextRule();
                                    iface.doEndif();
                                    
                                    exit = true;
                                    
                                    iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 7);
                                    
                                    // Rule R07 <----
                                }
                            }
                            else
                            {
                                if ( iface.isHasMoreConditions() )
                                {
                                    // Rule R08 ---->
                                    
                                    iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 8);
                                    iface.doElseIfConditionTitleWithOccEntryAndLabelYes();
                                    
                                    exit = true;
                                    
                                    iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 8);
                                    
                                    // Rule R08 <----
                                }
                                else
                                {
                                    // Rule R09 ---->
                                    
                                    iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 9);
                                    iface.doElseIfConditionTitleWithOccEntryAndLabelYes();
                                    iface.doAddListOfActions();
                                    iface.doNextRule();
                                    
                                    exit = true;
                                    
                                    iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 9);
                                    
                                    // Rule R09 <----
                                }
                            }
                        }
                    }
                }
                else
                {
                    if ( iface.isConditionStateIs() )
                    {
                        if ( iface.isHasMoreConditions() )
                        {
                            // Rule R10 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 10);
                            iface.doIfWithConditionTitleAndLabelYes();
                            
                            exit = true;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 10);
                            
                            // Rule R10 <----
                        }
                        else
                        {
                            // Rule R11 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 11);
                            iface.doIfWithConditionTitleAndLabelYes();
                            iface.doAddListOfActions();
                            iface.doNextRule();
                            iface.doEndif();
                            
                            exit = true;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 11);
                            
                            // Rule R11 <----
                        }
                    }
                    else
                    {
                        if ( iface.isHasMoreConditions() )
                        {
                            // Rule R12 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 12);
                            iface.doElseWithLabelNo();
                            iface.doNextCondition();
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 12);
                            
                            // Rule R12 <----
                        }
                        else
                        {
                            // Rule R13 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 13);
                            iface.doElseWithLabelNo();
                            iface.doAddListOfActions();
                            
                            exit = true;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191201.002528", 13, 13);
                            
                            // Rule R13 <----
                        }
                    }
                }
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190905b) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet

