// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet
// From decision table
// "/data/github/asciidoctorj-decisiontable-extension/src/main/resources/DecisionTableToPlantUMLActivityDiagram.lfet"
// 13.11.2019 01:02
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190905b) build in default

package com.uniqueck.asciidoctorj.lfet.puml.activity;

public final class DecisionTableToPlantUMLActivityDiagramRules
{
    public final void execute(IDecisionTableToPlantUMLActivityDiagram iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=com.uniqueck.asciidoctorj.lfet.puml.activity
        // $$InterfaceTraceAfterRule=true
        // $$InterfaceRuleGroups = true
        // $$InterfaceName=IDecisionTableToPlantUMLActivityDiagram
        // $$InterfaceRulesClassname=DecisionTableToPlantUMLActivityDiagramRules
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 1);
                iface.doParseDecisionTable();
                iface.doExtractLanguage();
                iface.doAddPlantumlTag();
                iface.doAdd4TimesHyphen();
                iface.doAddTitle();
                iface.doAddStart();
                iface.doGetFirstRule();
                iface.doGetFirstConditionOfFirstRule();
                
                ruleGroup = 2;
                exit = false;
                
                iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 1);
                
                // Rule R01 <----
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface.isLastConditionOfRule() )
                {
                    if ( iface.isHasMoreRules() )
                    {
                        if ( iface.isHasNextRuleSameCondition() )
                        {
                            // Rule R02 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 2);
                            iface.doAddActionsOfRule();
                            iface.doAddElse();
                            iface.doNextRule();
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 2);
                            
                            // Rule R02 <----
                        }
                        else
                        {
                            // Rule R03 ---->
                            
                            iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 3);
                            iface.doAddActionsOfRule();
                            iface.doAddEndif();
                            
                            ruleGroup = 3;
                            exit = false;
                            
                            iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 3);
                            
                            // Rule R03 <----
                        }
                    }
                    else
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 4);
                        iface.doAddActionsOfRule();
                        iface.doAddEndif();
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 4);
                        
                        // Rule R04 <----
                    }
                }
                else
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 5);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 5);
                    
                    // Rule R05 <----
                }
            }
            else
            {
                // Rule R06 ---->
                
                iface.doTrace("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 6);
                iface.doAddStop();
                iface.doAdd4TimesHyphen();
                
                exit = true;
                
                iface.doTraceAfterRule("DecisionTableToPlantUMLActivityDiagram", "20191113.010251", 6, 6);
                
                // Rule R06 <----
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190905b) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet

