// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet
// From decision table
// "/data/github/asciidoctorj-decisiontable-extension/src/main/resources/ConditionToPlantUMLActivityDiagram.lfet"
// 26.09.2019 00:01
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.1.5 (190905b) build in default

package com.uniqueck.asciidoctorj.lfet.puml.activity;

public interface IConditionToPlantUMLActivityDiagram
{
 
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$Package=org.uniqueck.asciidoctorj.extension.decisiontable.lfet
    // $$InterfaceTraceAfterRule=true
    // $$InterfaceRuleGroups = true
    // $$InterfaceName=IConditionToPlantUMLActivityDiagram
    // $$InterfaceRulesClassname=ConditionToPlantUMLActivityDiagramRules
    // Prolog Decision Table <----
    
    /** 
     * <b>C01: condition type is occurence table</b>
     */
    public boolean isConditionTypeIsOccurenceTable();
    
    /** 
     * <b>C02: condition state is</b>
     */
    public boolean isConditionStateIs();
    
    /** 
     * <b>C03: current occ entry is *</b>
     */
    public boolean isCurrentOccEntryIs();
    
    /** 
     * <b>C04: current occ entry is last</b>
     */
    public boolean isCurrentOccEntryIsLast();
    
    /** 
     * <b>C05: current occ entry is first</b>
     */
    public boolean isCurrentOccEntryIsFirst();
    
    /** 
     * <b>C06: has more conditions</b>
     */
    public boolean isHasMoreConditions();
    
    /** 
     * <b>A01: if with condition title and label yes</b>
     */
    public void doIfWithConditionTitleAndLabelYes();
    
    /** 
     * <b>A02: else with label no</b>
     */
    public void doElseWithLabelNo();
    
    /** 
     * <b>A03: else</b>
     */
    public void doElse();
    
    /** 
     * <b>A04: else if condition title with occ entry and label yes</b>
     */
    public void doElseIfConditionTitleWithOccEntryAndLabelYes();
    
    /** 
     * <b>A05: if condition title with occ entry and label yes</b>
     */
    public void doIfConditionTitleWithOccEntryAndLabelYes();
    
    /** 
     * <b>A06: add list of actions</b>
     */
    public void doAddListOfActions();
    
    /** 
     * <b>A07: endif</b>
     */
    public void doEndif();
    
    public void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);
    
    public void doTraceAfterRule(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (190905b) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet

